name: Auto Approve

on:
  pull_request_target:

jobs:
  auto-approve:
    runs-on: ubuntu-24.04
    if: github.actor == 'scala-steward' || github.actor == 'renovate[bot]'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v4.0.0
        with:
          github-token: "${{ secrets.AUTO_APPROVE_GITHUB_ACCESS_TOKEN }}"
      - name: Auto approve 1
        uses: hmarr/auto-approve-action@v4.0.0
        with:
          github-token: "${{ secrets.AUTO_APPROVE_GITHUB_ACCESS_TOKEN_1 }}"
